### ISSUE TITLE
Get rid of `harmonise` and `adjoint_test`

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/TemporalGPs.jl#93]
All the functionality has been now moved to `ChainRulesTestUtils` and should be used there.
This includes:
- [ ] Using `ChainRulesTestUtils.rand_tangent` rather than `FiniteDifferences.rand_tangent`
- [ ] Deprecate `harmonise`
- [ ] Deprecate `adjoint_test`

**Comment by willtebbutt** [comment]
Resolved by #129
