### ISSUE TITLE
Gradient for `KernelSum` and `KernelProduct` fail

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/TemporalGPs.jl#95]
The tests containing a sum of kernels have been commented out in `test/models/lti_sde.jl`, they should be added back and solved

**Comment by theogf** [comment]
Issues seems to stem from different Tangent types at the leaf level. It looks really hard to debug...

**Comment by theogf** [comment]
[UPDATE:]
So by using the `to_vec` approach with #98, now gradients are comparable but are not equal, they are left as broken for now. There is highly probably an error there somewhere.

**Comment by willtebbutt** [comment]
I can't find the example that you're talking about, so I'm going to close this (there aren't any failing examples left now that we're using Mooncake). Please feel free to reopen if you think I've missed something!
